# -*- coding: utf-8 -*-
"""GENERATIVE TEXT.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kAaNpx2EhNLAppV-yQ7brCsCf-DsMSgM
"""

!pip install transformers
!pip install torch

from transformers import GPT2LMHeadModel, GPT2Tokenizer
import torch

model_name = "gpt2"
tokenizer = GPT2Tokenizer.from_pretrained(model_name)
model = GPT2LMHeadModel.from_pretrained(model_name)


device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model.to(device).eval()

def generate_text(prompt, max_length=300):
    inputs = tokenizer.encode(prompt, return_tensors="pt").to(device)
    outputs = model.generate(
        inputs,
        max_length=max_length,
        num_return_sequences=1,
        no_repeat_ngram_size=2,
        temperature=0.9,
        top_k=50,
        top_p=0.95,
        do_sample=True,
        early_stopping=True
    )
    generated = tokenizer.decode(outputs[0], skip_special_tokens=True)
    paragraph = generated.strip().replace("\n", " ")


    if paragraph[-1] not in ".!?":
        paragraph += "."
    return paragraph


user_prompt = input("📥 Enter a topic for text generation: ")
result = generate_text(user_prompt)
print("\n📝 Generated Paragraph:\n")
print(result)

